import type { Metadata } from "next";
import { LegalMissing } from "../../components/legal-missing";
import { legalConfig } from "../../lib/site";

export const metadata: Metadata = { title: "Datenschutzerklärung", alternates: { canonical: "/datenschutz" } };

export default function PrivacyPage() {
  const configured = Boolean(legalConfig.operator && legalConfig.street && legalConfig.city && legalConfig.contactEmail && legalConfig.hostingProvider);
  return (
    <main id="main-content" className="legal-page">
      <div className="container legal-wrap">
        <span className="eyebrow">Rechtliches</span>
        <h1>Datenschutzerklärung</h1>
        {!configured ? <LegalMissing /> : null}
        <section><h2>1. Verantwortlicher</h2><p>{legalConfig.operator}{legalConfig.legalForm ? ` ${legalConfig.legalForm}` : ""}<br />KommunalHilfe<br />{legalConfig.street || "[Straße und Hausnummer noch zu ergänzen]"}<br />{legalConfig.city || "[Postleitzahl und Ort noch zu ergänzen]"}<br />E-Mail: <a href={`mailto:${legalConfig.contactEmail}`}>{legalConfig.contactEmail}</a><br />Telefon: {legalConfig.phone}</p></section>
        <section><h2>2. Hosting und Server-Protokolle</h2><p>Beim Aufruf dieser Website verarbeitet der Hostinganbieter technisch erforderliche Verbindungsdaten, insbesondere IP-Adresse, Zeitpunkt, angeforderte Ressource, Referrer, Browser- und Systeminformationen. Die Verarbeitung dient dem sicheren und stabilen Betrieb der Website.</p><p>Hostinganbieter: {legalConfig.hostingProvider || "[Hostinganbieter, Sitz und Datenschutzinformationen ergänzen]"}</p><p>Rechtsgrundlage und konkrete Speicherdauer sind vor Veröffentlichung anhand des tatsächlich eingesetzten Hostings zu ergänzen.</p></section>
        <section><h2>3. Anfrageformular</h2><p>Wenn Sie das Anfrageformular verwenden, verarbeiten wir die von Ihnen eingegebenen Angaben zur Bearbeitung und Beantwortung Ihrer Anfrage. Pflichtangaben sind Organisation, Einsatzort, Name, E-Mail-Adresse, Beschreibung und Einwilligungsbestätigung. Telefon und ausgewählte Leistung sind freiwillig.</p><p>Die Daten werden über einen serverseitigen Endpunkt an die konfigurierte dienstliche Empfängeradresse gesendet. Für den Versand ist technisch der Dienst Resend vorbereitet. Betreiber, Vertragsgrundlage, Datenstandort, Speicherdauer und gegebenenfalls Auftragsverarbeitung sind vor Aktivierung abschließend zu prüfen und hier konkret zu ergänzen.</p></section>
        <section><h2>4. Schutz vor automatisierten Anfragen</h2><p>Das Formular verwendet ein unsichtbares Honeypot-Feld, eine Herkunftsprüfung und eine einfache serverseitige Mengenbegrenzung. Dabei können zur Abwehr missbräuchlicher Anfragen kurzfristig IP-bezogene Zugriffsdaten verarbeitet werden.</p></section>
        <section><h2>5. Cookies und Reichweitenmessung</h2><p>In der ausgelieferten Grundkonfiguration setzt die Website keine eigenen Marketing- oder Analyse-Cookies ein und lädt keine externen Schriftarten. Wird später eine Reichweitenmessung, ein Karten- oder Medienanbieter ergänzt, muss dieser Abschnitt vor Aktivierung angepasst und gegebenenfalls eine Einwilligungslösung eingerichtet werden.</p></section>
        <section><h2>6. Externe Links</h2><p>Einzelne Wissensbeiträge können auf offizielle Informationsangebote verlinken. Erst beim Anklicken wird die externe Website aufgerufen; für deren Datenverarbeitung ist der jeweilige Betreiber verantwortlich.</p></section>
        <section><h2>7. Ihre Rechte</h2><p>Unter den gesetzlichen Voraussetzungen haben Sie das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit. Soweit eine Verarbeitung auf einer Einwilligung beruht, können Sie diese jederzeit mit Wirkung für die Zukunft widerrufen.</p><p>Bei einer Verarbeitung auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO können Sie aus Gründen Ihrer besonderen Situation Widerspruch einlegen. Gegen Direktwerbung ist ein Widerspruch jederzeit möglich. Für die Ausübung Ihrer Rechte genügt eine Nachricht an die oben genannte Kontaktadresse.</p><p>Sie können sich bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere an Ihrem Aufenthaltsort, Arbeitsplatz oder am Ort des vermuteten Verstoßes. In Baden-Württemberg ist dies der <a href="https://www.baden-wuerttemberg.datenschutz.de/">Landesbeauftragte für den Datenschutz und die Informationsfreiheit</a>.</p></section>
        <section><h2>8. Speicherdauer</h2><p>Anfragedaten werden nur so lange gespeichert, wie dies zur Bearbeitung, Anbahnung einer Zusammenarbeit und Erfüllung gesetzlicher Aufbewahrungspflichten erforderlich ist. Konkrete Fristen sind vor Veröffentlichung anhand des tatsächlichen Betriebsprozesses zu ergänzen.</p></section>
        <section><h2>9. Kontakt per E-Mail und Telefon</h2><p>Wir verarbeiten Ihre Kontaktdaten und die von Ihnen mitgeteilten Inhalte zur Beantwortung Ihres Anliegens und gegebenenfalls zur Vorbereitung eines Angebots. Bitte übermitteln Sie nur erforderliche Angaben und keine vertraulichen Bürger- oder Gesundheitsdaten.</p><p>Für Anfragen zu einem eigenen Vertrag oder vorvertraglichen Maßnahmen ist Art. 6 Abs. 1 lit. b DSGVO die Rechtsgrundlage. Bei dienstlichen Ansprechpartnern einer Kommune oder Organisation und sonstiger Korrespondenz ist die Rechtsgrundlage Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse liegt in der Bearbeitung der Anfrage und der geschäftlichen Kommunikation.</p><p>Das Kontaktpostfach wird bei Gmail geführt. Nachrichten und Anhänge werden daher auch durch Google verarbeitet. Weitere Informationen finden Sie in der <a href="https://policies.google.com/privacy?hl=de">Datenschutzerklärung von Google</a>. Die für das verwendete Konto geltenden Vertragsbedingungen und Übermittlungsregelungen sind vor dem regulären Betrieb abschließend zu prüfen.</p></section>
        <section><h2>10. Automatisierte Entscheidungen</h2><p>Die Website trifft keine automatisierten Entscheidungen mit rechtlicher oder ähnlich erheblicher Wirkung und erstellt keine entsprechenden Persönlichkeitsprofile.</p></section>
        <section><h2>11. Stand und offene Betriebsangaben</h2><p>Bearbeitungsstand: 11. September 2026. Diese Fassung ist ein Entwurf. Anschrift, tatsächliches Hosting, Protokollfristen, E-Mail-Verträge und gegebenenfalls Drittlandübermittlungen müssen vor Veröffentlichung abschließend bestätigt und ergänzt werden.</p><p>Für das vorgesehene Hosting und den vorbereiteten Formularversand sind insbesondere die <a href="https://vercel.com/legal/privacy-notice">Datenschutzhinweise von Vercel</a> und die <a href="https://resend.com/legal/privacy-policy">Datenschutzhinweise von Resend</a> zu berücksichtigen. Eine Aktivierung dieser Dienste wird durch diese Erklärung nicht vorgenommen.</p></section>
        <p className="legal-review-note">Diese technische Vorlage ersetzt keine datenschutzrechtliche Prüfung des tatsächlichen Website- und Geschäftsprozesses.</p>
      </div>
    </main>
  );
}
